config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  devise_for :users
  resources :profiles, only: [ :show, :new, :create, :edit, :update ]
  resources :thought_checks do
    resources :questions
  end
  resources :tasks

  get 'thought_checks/new_situation', to: 'thought_checks#new_situation', as: 'new_situation'
  # post 'thought_checks/create_situation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/models/thought_check.rb
class ThoughtCheck < ApplicationRecord
  attr_writer :current_step

  belongs_to :profile
  has_many :tasks
  has_many :question

  validates_presence_of :situation, :if => :situation?
  validates_presence_of :about, :if => :about?
  validates_presence_of :thought, :if => :thought?
  validates_presence_of :emotion, :if => :emotion?
  validates_presence_of :emotion_level, :if => :emotion_level?
  validates_presence_of :physiological, :if => :physiological?
  #validates_presence_of :trust, :if => :trust?

  def current_step
    @current_step || steps.first
  end

  def situation?
    @current_step == "situation"
  end

  def about?
    @current_step == "about"
  end

  def thought?
    @current_step == "thought"
  end

  def emotion?
    @current_step == "emotion"
  end

  def emotion_level?
    @current_step == "emotion_level"
  end

  def physiological?
    @current_step == "physiological"
  end

  #def trust?
  #  @current_step == "trust"
  #end

  def progressbar
    [['situation', 'Étape 1'], ['about', 'Étape 2'], ['thought', 'Étape 3'], ['emotion', 'Étape 4'], ['emotion_level', 'Étape 5'], ['physiological', 'Étape 6']]
  end

  def all_valid?
    steps.all? do |step|
      self.current_step = step
      valid?
    end
  end

  def steps
    %w[situation about thought emotion emotion_level physiological] 
    # I delete trust step (last one step)
  end

  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end

  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end

  def first_step?
    current_step == steps.first
  end

  def last_step?
    current_step == steps.last
  end


  def total(situation)
    maison ||= 0
    transports ||= 0
    travail ||= 0
    lit ||= 0
    magasin ||= 0
    vacances ||= 0
    sport ||= 0
    autre ||= 0
    total ||= 0
    # The purpose here is to count the number of thought check for each situation
    if situation == 'À la maison'
        maison += 1
      end

      if situation == 'Dans les transports'
        transports += 1
      end

      if situation == 'Au travail'
        travail += 1
      end

      if situation == 'Dans mon lit'
        lit += 1
      end

      if situation == 'Dans un magasin'
        magasin += 1
      end

      if situation == 'En vacances'
        vacances += 1
      end

      if situation == 'Au sport'
        sport += 1
      end

      if situation == 'Autre'
        autre += 1
      end

  end

  def maison(situation)
    if maison !
      maison << thought_check.situation
    end 
  end

end

app/controllers/thought_checks_controller.rb
class ThoughtChecksController < ApplicationController

  # before_action :set_thought_check, :only [ :show, :edit, :update, :destroy ]
  # I didn't understand why this line of code break my app ?

  def index
    @thought_checks = ThoughtCheck.all.where(profile_id: Profile.find_by_id(current_user.id))

    @thought_checks.each do |thought_check|
      #thought_check.total(thought_check.situation)
      @maison ||= 0
      @emotion_maison ||= []
      @emotion_maison_peur ||= []
      @emotion_maison_colere ||= []
      @emotion_maison_tristesse ||= []
      @emotion_maison_culpa ||= []
      @emotion_maison_haine ||= []
      @emotion_maison_frustra ||= []

      @transports ||= 0
      @emotion_transports ||= []
      @emotion_transports_peur ||= []
      @emotion_transports_colere ||= []
      @emotion_transports_tristesse ||= []
      @emotion_transports_culpa ||= []
      @emotion_transports_haine ||= []
      @emotion_transports_frustra ||= []

      @travail ||= 0
      @emotion_travail ||= []
      @emotion_travail_peur ||= []
      @emotion_travail_colere ||= []
      @emotion_travail_tristesse ||= []
      @emotion_travail_culpa ||= []
      @emotion_travail_haine ||= []
      @emotion_travail_frustra ||= []

      @lit ||= 0
      @emotion_lit ||= []
      @emotion_lit_peur ||= []
      @emotion_lit_colere ||= []
      @emotion_lit_tristesse ||= []
      @emotion_lit_culpa ||= []
      @emotion_lit_haine ||= []
      @emotion_lit_frustra ||= []

      @magasin ||= 0
      @emotion_magasin ||= []
      @emotion_magasin_peur ||= []
      @emotion_magasin_colere ||= []
      @emotion_magasin_tristesse ||= []
      @emotion_magasin_culpa ||= []
      @emotion_magasin_haine ||= []
      @emotion_magasin_frustra ||= []

      @vacances ||= 0
      @emotion_vacances ||= []
      @emotion_vacances_peur ||= []
      @emotion_vacances_colere ||= []
      @emotion_vacances_tristesse ||= []
      @emotion_vacances_culpa ||= []
      @emotion_vacances_haine ||= []
      @emotion_vacances_frustra ||= []

      @sport ||= 0
      @emotion_sport ||= []
      @emotion_sport_peur ||= []
      @emotion_sport_colere ||= []
      @emotion_sport_tristesse ||= []
      @emotion_sport_culpa ||= []
      @emotion_sport_haine ||= []
      @emotion_sport_frustra ||= []

      @autre ||= 0
      @emotion_autre ||= []
      @emotion_autre_peur ||= []
      @emotion_autre_colere ||= []
      @emotion_autre_tristesse ||= []
      @emotion_autre_culpa ||= []
      @emotion_autre_haine ||= []
      @emotion_autre_frustra ||= []

      #@total ||= 0
      if thought_check.situation == 'À la maison'
        @maison +=1
        @emotion_maison << thought_check.emotion
        if thought_check.emotion == 'Peur'
          @emotion_maison_peur << thought_check.emotion
        elsif thought_check.emotion == 'Colère'
          @emotion_maison_colere << thought_check.emotion
        elsif thought_check.emotion == 'Tristesse'
          @emotion_maison_tristesse << thought_check.emotion
        elsif thought_check.emotion == 'Culpabilité'
          @emotion_maison_culpa << thought_check.emotion
        elsif thought_check.emotion == 'Haine'
          @emotion_maison_haine << thought_check.emotion
        else thought_check.emotion == 'Frustration'
          @emotion_maison_frustra << thought_check.emotion
        end
      end
      if thought_check.situation == 'Dans les transports'
        @transports +=1
        @emotion_transports << thought_check.emotion
        if thought_check.emotion == 'Peur'
          @emotion_transports_peur << thought_check.emotion
        elsif thought_check.emotion == 'Colère'
          @emotion_transports_colere << thought_check.emotion
        elsif thought_check.emotion == 'Tristesse'
          @emotion_transports_tristesse << thought_check.emotion
        elsif thought_check.emotion == 'Culpabilité'
          @emotion_transports_culpa << thought_check.emotion
        elsif thought_check.emotion == 'Haine'
          @emotion_transports_haine << thought_check.emotion
        else thought_check.emotion == 'Frustration'
          @emotion_transports_frustra << thought_check.emotion
        end
      end
      if thought_check.situation == 'Au travail'
        @travail += 1
        @emotion_travail << thought_check.emotion
        if thought_check.emotion == 'Peur'
          @emotion_travail_peur << thought_check.emotion
        elsif thought_check.emotion == 'Colère'
          @emotion_travail_colere << thought_check.emotion
        elsif thought_check.emotion == 'Tristesse'
          @emotion_travail_tristesse << thought_check.emotion
        elsif thought_check.emotion == 'Culpabilité'
          @emotion_travail_culpa << thought_check.emotion
        elsif thought_check.emotion == 'Haine'
          @emotion_travail_haine << thought_check.emotion
        else thought_check.emotion == 'Frustration'
          @emotion_travail_frustra << thought_check.emotion
        end
      end

      if thought_check.situation == 'Dans mon lit'
        @lit += 1
        @emotion_lit << thought_check.emotion
        if thought_check.emotion == 'Peur'
          @emotion_lit_peur << thought_check.emotion
        elsif thought_check.emotion == 'Colère'
          @emotion_lit_colere << thought_check.emotion
        elsif thought_check.emotion == 'Tristesse'
          @emotion_lit_tristesse << thought_check.emotion
        elsif thought_check.emotion == 'Culpabilité'
          @emotion_lit_culpa << thought_check.emotion
        elsif thought_check.emotion == 'Haine'
          @emotion_lit_haine << thought_check.emotion
        else thought_check.emotion == 'Frustration'
          @emotion_lit_frustra << thought_check.emotion
        end
      end

      if thought_check.situation == 'Dans un magasin'
        @magasin += 1
        @emotion_magasin << thought_check.emotion
        if thought_check.emotion == 'Peur'
          @emotion_magasin_peur << thought_check.emotion
        elsif thought_check.emotion == 'Colère'
          @emotion_magasin_colere << thought_check.emotion
        elsif thought_check.emotion == 'Tristesse'
          @emotion_magasin_tristesse << thought_check.emotion
        elsif thought_check.emotion == 'Culpabilité'
          @emotion_magasin_culpa << thought_check.emotion
        elsif thought_check.emotion == 'Haine'
          @emotion_magasin_haine << thought_check.emotion
        else thought_check.emotion == 'Frustration'
          @emotion_magasin_frustra << thought_check.emotion
        end
      end

      if thought_check.situation == 'En vacances'
        @vacances += 1
        @emotion_vacances << thought_check.emotion
        if thought_check.emotion == 'Peur'
          @emotion_vacances_peur << thought_check.emotion
        elsif thought_check.emotion == 'Colère'
          @emotion_vacances_colere << thought_check.emotion
        elsif thought_check.emotion == 'Tristesse'
          @emotion_vacances_tristesse << thought_check.emotion
        elsif thought_check.emotion == 'Culpabilité'
          @emotion_vacances_culpa << thought_check.emotion
        elsif thought_check.emotion == 'Haine'
          @emotion_vacances_haine << thought_check.emotion
        else thought_check.emotion == 'Frustration'
          @emotion_vacances_frustra << thought_check.emotion
        end
      end

      if thought_check.situation == 'Au sport'
        @sport += 1
        @emotion_sport << thought_check.emotion
        if thought_check.emotion == 'Peur'
          @emotion_sport_peur << thought_check.emotion
        elsif thought_check.emotion == 'Colère'
          @emotion_sport_colere << thought_check.emotion
        elsif thought_check.emotion == 'Tristesse'
          @emotion_sport_tristesse << thought_check.emotion
        elsif thought_check.emotion == 'Culpabilité'
          @emotion_sport_culpa << thought_check.emotion
        elsif thought_check.emotion == 'Haine'
          @emotion_sport_haine << thought_check.emotion
        else thought_check.emotion == 'Frustration'
          @emotion_sport_frustra << thought_check.emotion
        end
      end

      if thought_check.situation == 'Autre'
        @autre += 1
        @emotion_autre << thought_check.emotion
        if thought_check.emotion == 'Peur'
          @emotion_autre_peur << thought_check.emotion
        elsif thought_check.emotion == 'Colère'
          @emotion_autre_colere << thought_check.emotion
        elsif thought_check.emotion == 'Tristesse'
          @emotion_autre_tristesse << thought_check.emotion
        elsif thought_check.emotion == 'Culpabilité'
          @emotion_autre_culpa << thought_check.emotion
        elsif thought_check.emotion == 'Haine'
          @emotion_autre_haine << thought_check.emotion
        else thought_check.emotion == 'Frustration'
          @emotion_autre_frustra << thought_check.emotion
        end
      end
    end    
    @transports
    @emotion_transports
    @travail
    @lit
    @magasin
    @vacances
    @sport
    @autre
    # method count which count each time thought_check.thought_check.situation = one situation
  end

  def show
    @thought_check = ThoughtCheck.find(params[:id])
    # I want to select only question about this thought
    @questions = Question.all.where(thought_check_id: params[:id])
    redirect_to new_thought_check_path unless @thought_check
  end

  def new
    session[:thought_check_params] ||= {}
    @thought_check = ThoughtCheck.new
    @thought_check.current_step = session[:thought_check_step]
  end

  def create
    @profile = Profile.find(current_user.id)
    session[:thought_check_params].deep_merge!(params[:thought_check]) if params[:thought_check]
    @thought_check = ThoughtCheck.new(session[:thought_check_params])
    @thought_check.profile = @profile
    @thought_check.current_step = session[:thought_check_step]
    if @thought_check.valid?
      if params[:previous_button] == "Retour"
        @thought_check.previous_step
      elsif @thought_check.last_step?

app/helpers/thought_checks_helper.rb
module ThoughtChecksHelper
end

app/views/thought_checks/_about_step.html.erb
<p>À propos de qui ou de quoi concerner cette contrariété ? </p>
<%= f.select(:about, [['De moi', 'De moi'],
                          ['Des autres', 'Des autres'],
                          ['Du passé', 'Du passé'],
                          ['Du futur', 'Du futur'],
                          ['Du monde', 'Du monde'],
                         ],{ :prompt => "d"},
                           { :multiple => false, :size => 5, :class => 'form' }
                         ) %>

app/views/thought_checks/_emotion_level_step.html.erb
<p>Quel est le niveau d'intensité de cette émotion ? </p>
<%= f.select(:emotion_level, [['10%', '10%'],
                          ['20%', '20%'],
                          ['30%', '30%'],
                          ['40%', '40%'],
                          ['50%', '50%'],
                          ['60%', '60%'],
                          ['70%', '70%'],
                          ['80%', '80%'],
                          ['90%', '90%'],
                          ['100%', '100%'],
                         ],{ :prompt => "Choisissez une réponse"},
                           { :multiple => false, :size => 10 }
                         ) %>

app/views/thought_checks/_emotion_step.html.erb
<p>Quelle émotion avez-vous ressenti durant cette contrariété ? </p>
<%= f.select(:emotion, [['Peur', 'Peur'],
                          ['Colère', 'Colère'],
                          ['Tristesse', 'Tristesse'],
                          ['Culpabilité', 'Culpabilité'],
                          ['Haine', 'Haine'],
                          ['Frustration', 'Frustration'],
                         ],{ :prompt => "Choisissez une réponse"},
                           { :multiple => false, :size => 6 }
                         ) %>

app/views/thought_checks/_physiological_step.html.erb
<p>Avez-vous ressenti sensation phyique durant cette contrariété ? </p>
<%= f.select(:physiological, [['Palpitations', 'Palpitations'],
                          ['Transpiration', 'Transpiration'],
                          ['Tremblements', 'Tremblements'],
                          ['Panique', 'Panique'],
                          ['Rien de tout cela', 'Rien de tout cela'],
                         ],{ :prompt => "Choisissez une réponse"},
                           { :multiple => false, :size => 5 }
                         ) %>

app/views/thought_checks/_situation_step.html.erb
<p>Où avez-vous été contrariété ? </p>
<%= f.select(:situation, [['À la maison', 'À la maison'],
                    ['Dans les transports', 'Dans les transports'],
                    ['Au travail', 'Au travail'],
                    ['Dans votre lit', 'Dans votre lit'],
                    ['Dans un magasin', 'Dans un magasin'],
                    ['En vacances', 'En vacances'],
                    ['Au sport', 'Au sport'],
                    ['Autre', 'Autre'],
                   ],{ :prompt => ""},
                     { :multiple => false, :size => 8 }
                   ) %>

app/views/thought_checks/_thought_step.html.erb
<p>À quoi ressemblé le plus votre pensée durant cette contrariété ?</p>
<% if @thought_check.about == 'De moi' %>
  <%= f.select(:thought, [['Si je n\'ai pas été embauché, c\'est que je ne vaux rien', 'Si je n\'ai pas été embauché, c\'est que je ne vaux rien'],
                          ['Si je n\'ai pas 20 sur 20 à cet examen, c\'est que je suis nul', 'Si je n\'ai pas 20 sur 20 à cet examen, c\'est que je suis nul'],
                          ['Elle n\'a pas voulu sortir avec moi ; je vois bien que je n\'arriverai jamais à sortir avec une fille', 'Elle n\'a pas voulu sortir avec moi ; je vois bien que je n\'arriverai jamais à sortir avec une fille'],
                          ['J\'ai été licencié de mon entreprise, ce n\'est pas étonnant, je rate tout ce que je fais dans la vie', 'J\'ai été licencié de mon entreprise, ce n\'est pas étonnant, je rate tout ce que je fais dans la vie'],
                          ['Je ne me sens pas de taille à affronter une situation, donc je suis un looser.', 'Je ne me sens pas de taille à affronter une situation, donc je suis un looser.'],
                         ],{ :prompt => "d"},
                           { :multiple => false, :size => 5, :class => 'form' }
                         ) %>
<% end %>
<% if @thought_check.about == 'Des autres' %>
   <%= f.select(:thought, [['Je lui ai laissé un message mais il ne m\'a pas rappelé, il ne me considère plus comme son ami.', 'Je lui ai laissé un message mais il ne m\'a pas rappelé, il ne me considère plus comme son ami.'],
                          ['Mon patron m\'a regardé de travers, il pense certainement me licencier', 'Mon patron m\'a regardé de travers, il pense certainement me licencier'],
                          ['J\'ai fait une erreur au travail, tout le monde va le savoir et je serai complètement ridicule aux yeux de tous.', 'J\'ai fait une erreur au travail, tout le monde va le savoir et je serai complètement ridicule aux yeux de tous.'],
                          ['Après tout ce que j\'ai fait pour lui, il pourrait au moins être reconnaissant.', 'Après tout ce que j\'ai fait pour lui, il pourrait au moins être reconnaissant.'],
                          ['Si mon fils ne travaille pas à l\'école, c\'est parce que je suis une mauvaise mère.', 'Si mon fils ne travaille pas à l\'école, c\'est parce que je suis une mauvaise mère.'],
                          ['Je n\'aime pas déplaire aux gens.', 'Je n\'aime pas déplaire aux gens.'],
                         ],{ :prompt => "d"},
                           { :multiple => false, :size => 5, :class => 'form' }
                         ) %>
<% end %>
<% if @thought_check.about == 'Du passé' %>
   <%= f.select(:thought, [['Je n\'arriverai jamais à sortir de mon passé.', 'Je n\'arriverai jamais à sortir de mon passé.'],
                          ['J\'ai raté ma vie à cause des erreurs de mon passé', 'J\'ai raté ma vie à cause des erreurs de mon passé'],
                          ['', ''],
                          ['', ''],
                          ['', ''],
                         ],{ :prompt => "d"},
                           { :multiple => false, :size => 5, :class => 'form' }
                         ) %>
<% end %>
<% if @thought_check.about == 'Du futur' %>
   <%= f.select(:thought, [['J\'ai peur de tomber malade moi ou l\'un de mes proches', 'J\'ai peur de tomber malade moi ou l\'un de mes proches'],
                          ['Je suis inquiet(e) à propos de l\'avenir', 'Je suis inquiet(e) à propos de l\'avenir'],
                          ['Rien ne s\'améliorera jamais', 'Rien ne s\'améliorera jamais'],
                          ['C\'est sans espoir', 'C\'est sans espoir'],
                          ['', ''],
                         ],{ :prompt => "d"},
                           { :multiple => false, :size => 5, :class => 'form' }
                         ) %>
<% end %>
<% if @thought_check.about == 'Du monde' %>
   <%= f.select(:thought, [['Ce monde est pourri', 'Ce monde est pourri'],
                          ['Les gens sont égoïstes', 'Les gens sont égoïstes'],
                          ['', ''],
                          ['', ''],
                          ['', ''],
                         ],{ :prompt => "d"},
                           { :multiple => false, :size => 5, :class => 'form' }
                         ) %>
<% end %>

app/views/thought_checks/_trust_step.html.erb
 <p>Quel est le pourcentage de confiance que vous avez vis-à-vis de cette pensée ?</p>
        <%= f.select(:trust, [['0%', '0%'],
                                  ['10%', '10%'],
                                  ['20%', '20%'],
                                  ['30%', '30%'],
                                  ['40%', '40%'],
                                  ['50%', '50%'],
                                  ['60%', '60%'],
                                  ['70%', '70%'],
                                  ['80%', '80%'],
                                  ['90%', '90%'],
                                  ['100%', '100%'],
                                 ],{ :prompt => "Choisissez une réponse"},
                                   { :multiple => false, :size => 11 }
                                 ) %>

app/views/thought_checks/destroy.html.erb
<h1>ThoughtChecks#destroy</h1>
<p>Find me in app/views/thought_checks/destroy.html.erb</p>

app/views/thought_checks/edit.html.erb
<h1>ThoughtChecks#edit</h1>
<p>Find me in app/views/thought_checks/edit.html.erb</p>

app/views/thought_checks/new.html.erb
<%= simple_form_for @thought_check, :html=> { class: 'text-center', id: 'ms-form'} do |f| %>
  
<div class="main-container">
  <div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <ul id="progressbar" style="margin-top: 150px;">
    <% @thought_check.progressbar.each_with_index do |step, index| %>
      <% if @thought_check.current_step == step[0] %>
        <li class ="active"><%= index + 1 %></li>
      <% else %>
        <li><%= index + 1 %></li>
      <% end %>
    <% end  %>
  </ul>
    <div class="card new-session card-form text-center">
          <%= f.error_notification %>
          <fieldset>
            <%= render "#{@thought_check.current_step}_step", :f => f %>
            <div class="next d-flex justify-content-center flex-nowrap pt-5">
              <%= f.submit "Retour", :name => "previous_button", class: "btn btn-dange call-to-action" ,id:"back" unless @thought_check.first_step? %>
              <%= f.submit "Continuer", class: "btn btn-success call-to-action" , id: "next"%>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>  
<script> 
  const options = document.querySelectorAll('option');
  function toggleClass() {
    this.classList.toggle('selected');
  }
  options.forEach(option => option.addEventListener('click', toggleClass));
  options.forEach(option => option.addEventListener('mouseover', toggleClass));
  options.forEach(option => option.addEventListener('mouseout', toggleClass));
</script>

app/views/thought_checks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-xs-offset-1">
      <div class="card big-card">
        <div class="card-left">
          <h2 class="master-title">Votre <b>pensée</b></h2>
          <p class="date"><%= @thought_check.created_at.strftime("%b %d, %Y") %></p>
          <P class="title-trust">Niveau de confiance</p>
          <h2 class="content-trust"><%= @thought_check.trust %></h2>
        </div>
        <div class="card-right">
          <div class="text">
            <h2 class="title"><b>Où ?</b></h2>
            <p><b>Situation :</b> <%= @thought_check.situation %></p>
            <hr>
            <h2 class="title"><b>Quoi ?</b> </h2>
            <p> <b>À propos de </b>: <%= @thought_check.about %></p>
            <p><b>Votre pensée :</b> <%= @thought_check.thought %></p>
            <hr>
            <h2 class="title"><b>Emotion ?</b> </h2>
            <p><%= @thought_check.emotion %></p>
            <p><b>Intensité de l'émotion :</b> <%= @thought_check.emotion_level %></p>
            <hr>
            <h2 class="title"><b>Sensation ?</b></h2>
            <p><%= @thought_check.physiological %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<hr>
<% if @questions != [] %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-xs-offset-1">
        <div class="card big-card">
          <div class="card-left-2">
            <h2 class="title"><b>Preuves +</b></h2>
            <p><%= @questions[0].positive_proof %></p>
            <hr>
            <h2 class="title"><b>Preuve -</b> </h2>
            <p><%= @questions[0].negative_proof %></p>
            <hr>
            <h2 class="title"><b>Pire des cas</b> </h2>
            <p><%= @questions[0].worst_case %></p>
            <hr>
            <h2 class="title"><b>Meilleur des cas</b></h2>
            <p><%= @questions[0].best_case %></p>
            <hr>
            <h2 class="title"><b>Le plus probable</b></h2>
            <p><%= @questions[0].realistic %></p>
          </div>
          <div class="card-right-2">
            <div class="text">
              <h2 class="master-title-2">questionnement</h2>
              <p class="date-2"><%= @questions[0].created_at.strftime("%b %d, %Y") %></p>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-xs-offset-1">
        <div class="card big-card">
          <div class="card-left-3">
            <h2 class="master-title">Votre <b>pensée</b> alternative</h2>
            <p class="date"><%= @questions[0].created_at.strftime("%b %d, %Y") %></p>
            <P class="title-trust">Niveau de confiance</p>
            <h2 class="content-trust"><%= @questions[0].new_trust %></h2>
          </div>
          <div class="card-right">
            <div class="text">
              <h2 class="title"><b>Quoi ?</b></h2>
              <p><b>Votre pensée alternative :</b> <%= @questions[0].alternative %></p>
              <hr>
              <h2 class="title"><b>Emotion ?</b> </h2>
              <p><%= @questions[0].new_emotion %></p>
              <p><b>Intensité de l'émotion :</b> <%= @questions[0].new_emotion_level %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<hr>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-xs-offset-5">
      <%= link_to new_thought_check_question_path(@thought_check) do %>
        <p class="btn" style="margin: 30px;">Se questionner</p>
      <% end %>
    </div>
  </div>
</div>

app/views/thought_checks/update.html.erb
<h1>ThoughtChecks#update</h1>
<p>Find me in app/views/thought_checks/update.html.erb</p>