config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  devise_for :users
  resources :profiles, only: [ :show, :new, :create, :edit, :update ]
  resources :thought_checks do
    resources :questions
  end
  resources :tasks

  get 'thought_checks/new_situation', to: 'thought_checks#new_situation', as: 'new_situation'
  # post 'thought_checks/create_situation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/views/shared/_card.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-12 col-xs-offset-1">
        <%= link_to(thought_check_path(thought_check.id)) do %>
        <div class="card big-card">
          <div class="card-left">
            <h2 class="master-title">Votre <b>pensée</b></h2>
            <p class="date"><%= thought_check.created_at.strftime("%b %d, %Y") %></p>
            <P class="title-trust">Niveau de confiance</p>
            <h2 class="content-trust"><%= thought_check.trust %></h2>
          </div>
          <div class="card-right">
            <div class="text">
              <h2 class="title"><b>Où ?</b></h2>
              <p><b>Situation :</b> <%= thought_check.situation %></p>
              <hr>
              <h2 class="title"><b>Quoi ?</b> </h2>
              <p> <b>À propos de </b>: <%= thought_check.about %></p>
              <p><b>Votre pensée :</b> <%= thought_check.thought %></p>
              <hr>
              <h2 class="title"><b>Emotion ?</b> </h2>
              <p><%= thought_check.emotion %></p>
              <p><b>Intensité de l'émotion :</b> <%= thought_check.emotion_level %></p>
              <hr>
              <h2 class="title"><b>Sensation ?</b></h2>
              <p><%= thought_check.physiological %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/shared/_circle.html.erb
<svg class="progress">
    <circle class="progress__meter" cx="60" cy="60" r="54" stroke-width="12" />
    <circle class="progress__value" cx="60" cy="60" r="54" stroke-width="12" />
    <text class="text-svg" x="35" y="0" transform="rotate(90 20,40)" fill="white">
      <tspan x="33" y="0" transform="rotate(90 20,40)" style=" font-size:22px;">
        <%= @emotion_maison_colere.count %> 
      </tspan>
      <tspan x="17" y="20" transform="rotate(90 20,40)" style=" font-size:16px;">
        Colère 
      </tspan>
    </text>
</svg>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag('logo.png') %>
  </a>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>