config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  devise_for :users
  resources :profiles, only: [ :show, :new, :create, :edit, :update ]
  resources :thought_checks do
    resources :questions
  end
  resources :tasks

  get 'thought_checks/new_situation', to: 'thought_checks#new_situation', as: 'new_situation'
  # post 'thought_checks/create_situation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <%= image_tag("trust.jpg", size: "200x250", class: "img")%>
    <h2 style="color: #FE7F2D; ">Mind</h2>
    <p style="color: white;">Remettre en question ses pensées, <br>passer à l'action pour changer</p>
    <% if current_user  %>
      <%= link_to(new_thought_check_path) do %>
        <p class="btn">Commencer</p>
      <% end %>
    <% else %>
      <%= link_to(new_user_registration_path) do %>
        <p class="btn">S'inscrire</p>
      <% end %>
    <% end %>
  </div>
</div>
<!-- A loose HTML + CSS translation of Dribble shot "Cycling" by Moncho Massé -->

<!-- Box to contain the bike -->
<div class="box">
  <!-- The Whole Bike -->
  <div class="bike">
    <!-- Components of the bike -->
    <!-- Back wheel -->
    <div class="back-wheel">
      <!-- Inside the wheel -->
      <div class="cassette">
        <!-- Spokes ~ the numbers are clock number orientation-->
        <div class="_12-6"></div>
        <div class="_1-7"></div>
        <div class="_2-8"></div>
        <div class="_3-9"></div>
        <div class="_4-10"></div>
        <div class="_5-11"></div>
      </div>
    </div>
    <div class="hub"></div>

    <!-- Front wheel -->
    <div class="front-wheel">
     <!-- Inside the wheel -->
      <div class="cassette">
        <!-- Spokes -->
        <div class="_12-6"></div>
        <div class="_1-7"></div>
        <div class="_2-8"></div>
        <div class="_3-9"></div>
        <div class="_4-10"></div>
        <div class="_5-11"></div>
        <div class="_6-12"></div>
      </div>
    </div>

    <!-- Handlebar -->
    <div class="handlebar">
      <div class="bar headset"></div>
      <div class="bar stem"></div>
      <div class="bar hb1"></div>
      <dv class="bar hb2"></div>
    </div>

    <!-- Seat -->
    <div class="seat">
    </div>

    <!-- Bike frame -->
    <div class="body-frame">
      <div class="bk-upper"></div>
      <div class="bk-lower"></div>
      <div class="fr-upper"></div>
      <div class="fr-lower"></div>
      <div class="seat-frame">
        <div class="seatpost"></div>
      </div>
      <div class="handlebar-frame"></div>
    </div>


    <!-- Crankset -->
    <div class="crank">
    </div>

    <div class="crankset">
    </div>

    <!-- Chain -->
    <div class="chain-upp"></div>
    <div class="chain-lo"></div>

    <!-- Bike Shadow -->
  <div class="bike-shadow"></div>

     <!-- Streaks of ground-light -->
  <div class="streak1"></div>
  <div class="streak2"></div>
  <div class="streak3"></div>
  <div class="streak4"></div>


  <!--Girl-->
  <div class="girl">
    <!--HEAD-->
    <div class="face">
      <div class="l-eye"></div>
      <div class="r-eye"></div>
      <div class="nose"></div>
      <div class="mouth"></div>
      <div class="ear">
        <div class="ear-shadow"></div>
      </div>
      <div class="l-cheek"></div>
      <div class="r-hair"></div>
      <div class="l-hair"></div>
      <div class="jaw-shadow"></div>
    </div>

    <div class="ponytail"></div>

     <div class="neck">
       <div class="neck-shadow"></div>
     </div>


    <!-- TORSO -->
    <div class="belly">
      <div class="back-shadow"></div>
    </div>
    <div class="pelvic-reg"></div>

    <div class="chest">
      <!-- ARMS -->
      <div class="r-arm">
        <div class="r-sleeve"></div>
        <div class="r-a-shadow"></div>
      </div>


       </div>

    <div class="l-arm">
       <div class="l-sleeve"></div>
      <div class="l-a-shadow"></div>
    </div>

    <!-- Legs -->
    <!-- Right Leg -->
    <div class="r-thigh">
      <div class="r-pants"></div>
      <div class="r-shadow"></div>
      <div class="r-calf">
        <!-- Sock -->
        <div class="sock">
          <div class="blue-top"></div>
          <!-- Shoe -->
          <div class="shoe-base">
            <div class="shoe-lining"></div>
            <div class="toecap"></div>
            <div class="heelcap"></div>
            <div class="shoetongue"></div>
            <div class="lace1"></div>
            <div class="lace2"></div>
            <div class="pedal"></div>
          </div>
        </div>
      </div>
    </div>

    <!-- Left Leg -->
     <div class="l-thigh">
       <div class="l-shadow"></div>
      <div class="l-calf">
        <div class="darker sock">
          <div class="blue-top" id="dark-blue"></div>
          <div class="shoe-base">
            <div class="shoe-lining"></div>
            <div class="toecap"></div>
            <div class="heelcap"></div>
            <div class="shoetongue"></div>
            <div class="lace lace1"></div>
            <div class="lace lace2"></div>
            <div class="pedal"></div>
          </div>
        </div>
      </div>
      <div class="l-pants"></div>
     </div>




  <!-- End of Girl -->
  </div>



  <!-- End of Bike -->
  </div>

  <!-- Environment -->
  <!-- Wind -->
<!--   <div class="w1"></div>
  <div class="w2"></div>
  <div class="w3"></div> -->

<!-- End of box -->
</div>


<div class="container"> 
  <div class="row"> 
    <div class="col-xs-12"> 
      <h2 class="title-features">Mind</h2>
    </div>
  </div>
   <div class="row"> 
    <div class="col-xs-12 col-md-4"> 
      <p class="feature"><span style="color: #FE7F2D;">1.</span> J'écris ma pensée </p>
    </div>
    <div class="col-xs-12 col-md-4"> 
      <p class="feature"><span style="color: #FE7F2D;">2.</span> Je la remets en question</p>
    </div>
    <div class="col-xs-12 col-md-4"> 
      <p class="feature"><span style="color: #FE7F2D;">3.</span> Je pense différement</p>
    </div>
  </div>
</div>